Resources:
  AskLlamaAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Ask LLM API
      StageName: Prod
  AskLlamaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 300
      PackageType: Image
      ImageConfig:
        Command: ["main.handler"]
      Events:
        AskLlama:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AskLlamaAPI
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1